// === AUTO-GENERATED FILE ===
// Generated by generate-mysamples.js
// 2025-11-03T21:10:45.059Z

register("mysamples", () => ({
  baseUrl: "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/",
  files: [
  "anime/Yamete0.mp3",
  "anime/Yamete1.mp3",
  "anime/Yamete2.mp3",
  "anime/Yamete3.mp3",
  "anime/Yamete4.mp3",
  "curse/cheh0.mp3",
  "curse/cheh1.mp3",
  "curse/cheh2.mp3",
  "curse/cheh3.mp3",
  "file_systemx86/filesys0.mp3",
  "file_systemx86/filesys1.mp3",
  "inari/inari0.mp3",
  "inari/inari1.mp3",
  "inari/inari10.mp3",
  "inari/inari11.mp3",
  "inari/inari12.mp3",
  "inari/inari13.mp3",
  "inari/inari15.mp3",
  "inari/inari16.mp3",
  "inari/inari17.mp3",
  "inari/inari2.mp3",
  "inari/inari3.mp3",
  "inari/inari4.mp3",
  "inari/inari5.mp3",
  "inari/inari6.mp3",
  "inari/inari7.mp3",
  "inari/inari8.mp3",
  "inari/inari9.mp3",
  "pol/lsmango.mp3",
  "pol/tpasriche.mp3",
  "xul/xul0.mp3",
  "xul/xul1.mp3",
  "xul/xul2.mp3",
  "xul/xul4.mp3",
  "xul/xul5.mp3",
  "xul/xul6.mp3",
  "xul/xul7.mp3",
  "xul/xul8.mp3",
  "xul/xul9.mp3"
]
}));

console.log("✅ Loaded 39 custom samples from mysamples pack.");