// === AUTO-GENERATED FILE ===
// Generated by generate-mysamples.js
// 2025-11-03T21:32:15.787Z

register("mysamples", () => ({
  baseUrl: "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/",
  files: {
  "Yamete0": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/anime/Yamete0.mp3",
  "Yamete1": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/anime/Yamete1.mp3",
  "Yamete2": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/anime/Yamete2.mp3",
  "Yamete3": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/anime/Yamete3.mp3",
  "Yamete4": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/anime/Yamete4.mp3",
  "cheh0": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/curse/cheh0.mp3",
  "cheh1": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/curse/cheh1.mp3",
  "cheh2": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/curse/cheh2.mp3",
  "cheh3": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/curse/cheh3.mp3",
  "filesys0": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/file_systemx86/filesys0.mp3",
  "filesys1": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/file_systemx86/filesys1.mp3",
  "inari0": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari0.mp3",
  "inari1": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari1.mp3",
  "inari10": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari10.mp3",
  "inari11": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari11.mp3",
  "inari12": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari12.mp3",
  "inari13": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari13.mp3",
  "inari15": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari15.mp3",
  "inari16": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari16.mp3",
  "inari17": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari17.mp3",
  "inari2": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari2.mp3",
  "inari3": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari3.mp3",
  "inari4": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari4.mp3",
  "inari5": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari5.mp3",
  "inari6": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari6.mp3",
  "inari7": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari7.mp3",
  "inari8": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari8.mp3",
  "inari9": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/inari/inari9.mp3",
  "lsmango": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/pol/lsmango.mp3",
  "tpasriche": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/pol/tpasriche.mp3",
  "xul0": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul0.mp3",
  "xul1": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul1.mp3",
  "xul2": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul2.mp3",
  "xul4": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul4.mp3",
  "xul5": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul5.mp3",
  "xul6": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul6.mp3",
  "xul7": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul7.mp3",
  "xul8": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul8.mp3",
  "xul9": "https://cdn.jsdelivr.net/gh/Lumpen-86/samples-packs@main/samples/xul/xul9.mp3"
}
}));

console.log("✅ Loaded 39 custom samples from mysamples pack.");