// === AUTO-GENERATED FILE ===
// Generated by generate-mysamples.js
// 2025-11-03T21:52:18.300Z

samples({
  anime_Yamete0: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/anime/Yamete0.mp3",
  anime_Yamete1: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/anime/Yamete1.mp3",
  anime_Yamete2: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/anime/Yamete2.mp3",
  anime_Yamete3: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/anime/Yamete3.mp3",
  anime_Yamete4: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/anime/Yamete4.mp3",
  curse_cheh0: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/curse/cheh0.mp3",
  curse_cheh1: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/curse/cheh1.mp3",
  curse_cheh2: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/curse/cheh2.mp3",
  curse_cheh3: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/curse/cheh3.mp3",
  file_systemx86_filesys0: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/file_systemx86/filesys0.mp3",
  file_systemx86_filesys1: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/file_systemx86/filesys1.mp3",
  inari_inari0: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari0.mp3",
  inari_inari1: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari1.mp3",
  inari_inari10: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari10.mp3",
  inari_inari11: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari11.mp3",
  inari_inari12: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari12.mp3",
  inari_inari13: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari13.mp3",
  inari_inari15: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari15.mp3",
  inari_inari16: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari16.mp3",
  inari_inari17: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari17.mp3",
  inari_inari2: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari2.mp3",
  inari_inari3: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari3.mp3",
  inari_inari4: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari4.mp3",
  inari_inari5: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari5.mp3",
  inari_inari6: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari6.mp3",
  inari_inari7: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari7.mp3",
  inari_inari8: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari8.mp3",
  inari_inari9: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/inari/inari9.mp3",
  pol_lsmango: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/pol/lsmango.mp3",
  pol_tpasriche: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/pol/tpasriche.mp3",
  xul_xul0: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul0.mp3",
  xul_xul1: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul1.mp3",
  xul_xul2: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul2.mp3",
  xul_xul4: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul4.mp3",
  xul_xul5: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul5.mp3",
  xul_xul6: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul6.mp3",
  xul_xul7: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul7.mp3",
  xul_xul8: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul8.mp3",
  xul_xul9: "https://raw.githubusercontent.com/Lumpen-86/samples-packs/main/samples/xul/xul9.mp3"
});

console.log("✅ Loaded 39 custom samples from mysamples pack.");